job('Build-SB-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/sohelxes1/movie-catalog-service.git", '*/master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}

